version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: fraud_gen_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fraud_gen_network

  mlflow:
    image: python:3.9-slim
    container_name: fraud_gen_mlflow
    command: echo "MLflow will be configured later"
    networks:
      - fraud_gen_network

volumes:
  postgres_data:

networks:
  fraud_gen_network:
    driver: bridge
